# The key value pairs found below are available within the templates.
# {{site_name}}, {{url}}, {{copyright}} and {{analytics_code}}

:site_name: Katherine J Lee
:url: http://www.katherinejlee.com/
:copyright: 2010
:analytics_code: UA-11602695-2