:headline: About
:body: | 
  Katherine Lee is an artist living and playing from her home in the San
  Francisco Bay area.

  She started Playing from Home in several incarnations. It began as a
  (now-extinct) blog of ambitious unfinished projects, which quickly
  became a busy one-girl operation that churned out handmade
  objects—felt animals, painted chairs, paper garlands, stamps, and
  finally home textiles.

  Currently, [Playing from Home](http://katherinejlee.etsy.com) is a collection of bed and table linens
  inspired by Katherine’s original illustrations. The designs are
  intended to be both funny and beautiful—a means of encouraging
  engagement and pleasure with objects found in the home every day.
  Because she is always looking for ways to improve her own nest,
  Katherine is a firm believer in buying, keeping and collecting only
  what you love.

  Despite the arguably superior weather in SF, Katherine holds deep
  affection for New England, where she received her BA from Williams
  College in 2008. She plans on a very gradual return to both the East
  Coast and academia to pursue fiction, the reading and writing of which
  are first and foremost in her mind.
  
  You can follow her on [twitter](http://twitter.com/playingfromhome), [facebook](http://www.facebook.com/pages/Oakland-CA/Playing-from-Home/175819432059), or her [blog](http://blog.katherinejlee.com).
  
:profile: true
:contact: false