:headline: Shop Online
:body: |
    If you're interested in wholesale orders, [let's talk](http://katherinejlee.wufoo.com/forms/wholesale-inquiries/).
:shop:
    :etsyembed: "<script type='text/javascript' src='http://www.etsy.com/etsy_mini.js'></script><script type='text/javascript'>new EtsyNameSpace.Mini(6917392, 'shop','gallery',4,5).renderIframe();</script>"